name: Test

on:
  workflow_dispatch:
  push: { branches: [ "main", "develop" ] }

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: true
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check tput
        shell: bash
        continue-on-error: true
        run: |
          printf "TERM=%s\n" "$TERM"
          if command -v tput >/dev/null 2>&1; then
            if tput colors &>/dev/null && [ "$(tput colors)" -ge 256 ]; then
              export TERM=xterm-256color
              echo "$(tput setaf 4)COLORS $(tput colors)$(tput sgr0)"
            else
              export TERM=xterm
              echo "$(tput setaf 4)COLORS $(tput colors)$(tput sgr0)"
            fi
          fi
          printf "TERM=%s\n" "$TERM"
          echo 'Finished'
      - uses: actions/checkout@v4
        with: { submodules: 'true' }
      - name: Setup Bats and Bats Libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.0
        with:
          support-path: "${{ github.workspace }}/tests/bats-support"
          assert-path: "${{ github.workspace }}/tests/bats-assert"
          detik-path: "${{ github.workspace }}/tests/bats-detik"
          file-path: "${{ github.workspace }}/tests/bats-file"
      - name: Run Bats Tests
        working-directory: ${{ github.workspace }}/tests
        shell: bash
        run: bats ./
      - name: Run Additional Tests
        working-directory: ${{ github.workspace }}/tests
        shell: bash
        run: bash additional.sh
      - name: Run Additional Tests on Docker Debian
        if: startsWith(runner.os, 'Linux')
        working-directory: ${{ github.workspace }}/tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/tests \
            debian:latest bash -c "bash additional.sh"
