name: BATS Tests

on:
  workflow_dispatch:
  push: { branches: [ "main", "develop" ] }

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, windows-2022 ]
      fail-fast: true
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.0
        with:
          support-path: "${{ github.workspace }}/tests/bats-support"
          assert-path: "${{ github.workspace }}/tests/bats-assert"
          detik-path: "${{ github.workspace }}/tests/bats-detik"
          file-path: "${{ github.workspace }}/tests/bats-file"
      - name: Run Bats tests
        working-directory: ${{ github.workspace }}/tests
        shell: bash
        run: bats ./
